---
- hosts: barman
  tasks:
    - name: Servers registered on barman
      command: barman list-server
      register: barman_list_server
      become: true
      become_method: sudo
      become_user: barman
    - debug:
        msg: "{{ barman_list_server.stdout }}"