---
- hosts: barman
  tasks:
    - command: barman list-server
      register: barman_list_server
      become: true
      become_method: sudo
      become_user: barman
    - debug:
        var: barman_list_server.stdout_lines