---
- hosts: barman
  tasks:
    - name: add source repository into source list
      apt_repository:
        repo: deb http://apt.postgresql.org/pub/repos/apt/ jessie-pgdg main
        state: present
        filename: '/etc/apt/sources.list.d/pgdg.list'

    - name: import the repository signing key
      apt_key:
        url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
        state: present

    - name: update the package lists
      apt: 
        update_cache: yes

    - name: Install Barman
      apt:
        name: barman

    - name: Install postgresql
      apt:
        name: postgresql-9.6

    - name: install repmgr
      apt:
        name: repmgr

    - name: Copy barman server configuration into /etc/barman.d
      template: 
        src: "{{ lookup('env', 'HOME') }}/.dbadmin/config/barman/barman.conf"
        dest: /etc/barman.conf

    - name: Copy database server pg's configuration into /etc/barman.d
      template: 
        src: "{{ lookup('env', 'HOME') }}/.dbadmin/config/barman/pg.j2"
        dest: /etc/barman.d/pg.conf


    - name: Copy database server standby1's configuration into /etc/barman.d
      template: 
        src: "{{ lookup('env', 'HOME') }}/.dbadmin/config/barman/standby1.j2"
        dest: /etc/barman.d/standby1.conf

    - name: Copy database server standby2's configuration into /etc/barman.d
      template: 
        src: "{{ lookup('env', 'HOME') }}/.dbadmin/config/barman/standby2.j2"
        dest: /etc/barman.d/standby2.conf

    - name: install pip
      apt:
        name: python-pip

    - name: install pexpect
      pip:
        name: pexpect

    - name: generate ssh keys
      expect: 
        command: ssh-keygen -t rsa
        responses:
          'Enter file in which to save the key \(/var/lib/barman/.ssh/id_rsa\):': "\n"
          'Enter passphrase \(empty for no passphrase\):': "\n"
          'Enter same passphrase again:': "\n"
      become: true
      become_method: sudo
      become_user: barman
      creates: /var/lib/barman/.ssh/id_rsa

    - name: fetch the public key of barman to store in the local box
      fetch:
        src: /var/lib/barman/.ssh/id_rsa.pub
        dest: /tmp

    - name: create incoming wal directory for master server
      file:
        path: /var/lib/barman/{{ hostvars[groups['master'][0]]['hostname'] }}/incoming
        state: directory
        owner: barman
        group: barman
        mode: 0755

    - name: create incoming wal directory for standby1 server
      file:
        path: /var/lib/barman/{{ hostvars[groups['standby1'][0]]['hostname'] }}/incoming
        state: directory
        owner: barman
        group: barman
        mode: 0755

    - name: create incoming wal directory for standby2 server
      file:
        path: /var/lib/barman/{{ hostvars[groups['standby2'][0]]['hostname'] }}/incoming
        state: directory
        owner: barman
        group: barman
        mode: 0755